config/routes.rb
Qoom::Application.routes.draw do

  devise_for :users

  match 'mail/new' => 'mail#create'

  resources :demands
  resources :users do
    resources :rooms do
      resources :questions do
        get "commentary", :on => :collection
      end
    end
  end

  authenticated :user do
    root :to => "top#index"
  end

  unauthenticated :user do
    root :to => "welcome#index"
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_one :rooms_questions
  has_one :room, :through=>:rooms_questions

  attr_accessible :content

  validates :content, :presence => true

  scope :sorted_created_at_desc, order("created_at desc")
  
  scope :newest, lambda { |last_time| where("created_at > ?", last_time).order("created_at desc") }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @room = Room.find(params[:room_id])
    @questions = @room.questions.sorted_created_at_desc
    respond_to do |format|
      format.html # index.html.erb
      format.js   { render action: "refresh.js.erb" }
    end
  end

  # GET /questions
  # GET /questions.json
  def commentary
    @room = Room.find(params[:room_id])
    if params[:last_time]
      @questions = @room.questions.newest( params[:last_time] )
    else
      @questions = [@room.questions.sorted_created_at_desc.first]
    end
    respond_to do |format|
      format.html # commentary.html.erb
      format.js   { render action: "commentary.js.erb" }
    end
  end

  # # GET /questions/1
  # # GET /questions/1.json
  # def show
  #   # @question = Question.find(params[:id])

  #   # respond_to do |format|
  #   #   format.html # show.html.erb
  #   #   format.json { render json: @question }
  #   # end
  # end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @room = Room.find(params[:room_id])
    @questions = @room.questions.sorted_created_at_desc
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # # GET /questions/1/edit
  # def edit
  #   # @question = Question.find(params[:id])
  # end

  # POST /questions
  # POST /questions.json
  def create
    @room = Room.find(params[:room_id])
    respond_to do |format|
      @room.questions.create( params[:question] )
      @question = Question.new
      @questions = @room.questions.sorted_created_at_desc
      format.js { render action: "create.js.erb" }
    end
  end

  # # PUT /questions/1
  # # PUT /questions/1.json
  # def update
  #   # @question = Question.find(params[:id])

  #   # respond_to do |format|
  #   #   if @question.update_attributes(params[:question])
  #   #     format.html { redirect_to @question, notice: 'Question was successfully updated.' }
  #   #     format.json { head :no_content }
  #   #   else
  #   #     format.html { render action: "edit" }
  #   #     format.json { render json: @question.errors, status: :unprocessable_entity }
  #   #   end
  #   # end
  # end

  # # DELETE /questions/1
  # # DELETE /questions/1.json
  # def destroy
  #   # @question = Question.find(params[:id])
  #   # @question.destroy

  #   # respond_to do |format|
  #   #   format.html { redirect_to questions_url }
  #   #   format.json { head :no_content }
  #   # end
  # end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def print_content(text)
    raw(url2link(html_escape(text).gsub(/\r\n|\r|\n/, "<br />")))
  end

  def url2link(text, options={})
    target = options[:target] || '_blank'
    URI.extract(text).uniq.each{|url|
      text.gsub!(url, "<a href='#{url}' target='#{target}'>#{truncate(url, :length => 40)}</a>")
    }
    return text
  end
end

app/views/questions/_form.html.erb
<%= form_for [current_user,@room, @question], remote: true do |f| %>
  <div class="control-group">
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area',:placeholder => "（必須）質問内容", :size=>"120x5" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit '質問', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/questions/_list.html.erb
<%- model_class = Question -%>
<table class="table table-striped">
  <% @questions.each_with_index do |question, index| %>
    <tr>
      <td>
      	<span style="color: gray;"><%= @questions.size - index %>:&nbsp;
        <%= question.created_at.strftime("%Y/%m/%d %H:%M:%S") %></span></br>
      	<%= print_content( question.content ) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/questions/_realtime.html.erb
<%= link_to "", commentary_user_room_questions_path( current_user.id, @room.id, :last_time => @questions.first.created_at ), method: :get, remote: true, id: :a_questions_list %>

<% @questions.each_with_index do |question, index| %>
<input type="hidden" name="comment_text_<%= index %>" value=
  "<%= question.content %>"
 />
<% end %>

app/views/questions/commentary.html.erb
<div class="span12">

	<div class="page-header">
	  <h1>
      <%= image_tag("commentary.png") %>
	  </h1>
	</div>

  <div class="row-fluid">
      <input type="hidden" id="comment_button" />
      <div id="comment_view" class="span11" />
      <div id='questions_list' ><%= render 'questions/realtime', :questions => @questions %></div>
  </div>

</div>

app/views/questions/commentary.js.erb
$("#questions_list").html("<%=j render 'questions/realtime', :questions => @questions %>");

app/views/questions/create.js.erb
$("#question_content").val("");

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<div class="span3"></div>
<div class="span6">
  <div class="page-header">
    <h1><%= @room.name %></br>
    	質問一覧
        <%= link_to "", user_room_questions_path( current_user.id, @room.id ), method: :get, remote: true, id: :a_questions_list %>
    </h1>
  </div>
  <div id='questions_list' ><%= render 'questions/list', :questions => @questions %></div>
</div>
<div class="span3"></div>

app/views/questions/new.html.erb
<div class="row">
  <div class="span4"></div>
  <div class="span4">
    <div class="page-header page-header-no-bottom">
    	<h1><%= @room.name %></h1>
    </div>
  	<div class="accordion" id="accordion2">
   	  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne"><i class="icon-hand-down"></i>&nbsp;質問の投稿</a>
	  <div id="collapseOne" class="accordion-body collapse in">
	    <div class="accordion-inner">
		  <%= render :partial => 'form' %>
		</div>
	  </div>
	</div>
  </div>
  <div class="span4"></div>
</div>

<div class="row">
  <div class="span4"></div>
  <div class="span4">
    <%= link_to "", user_room_questions_path( current_user.id, @room.id ), method: :get, remote: true, id: :a_questions_list %>
	<div id='questions_list' ><%= render 'questions/list', :questions => @questions %></div>
  </div>
  <div class="span4"></div>
</div>

app/views/questions/refresh.js.erb
$("#questions_list").html("<%=j render 'questions/list', :questions => @questions %>");

app/views/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nickname) %>:</strong></dt>
  <dd><%= @question.nickname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @question.content %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              questions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_question_path(@question), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              question_path(@question),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>