config/routes.rb
Qoom::Application.routes.draw do

  devise_for :users

  match 'mail/new' => 'mail#create'

  resources :demands
  resources :users do
    resources :rooms do
      resources :questions do
        get "commentary", :on => :collection
      end
    end
  end

  authenticated :user do
    root :to => "top#index"
  end

  unauthenticated :user do
    root :to => "welcome#index"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :users_rooms
  has_many :rooms, :through=>:users_rooms

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :account

  validates :account,:presence=>true,:uniqueness => true, :length=>{:maximum=>20}

  # scope :guest, lambda { where(:account=>'guest').first }
  scope :guest, where(:account=>'guest')

  def email_required?
    false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # # GET /users/1
  # # GET /users/1.json
  # def show
  #   @user = User.find(params[:id])

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @user }
  #   end
  # end

  # # GET /users/new
  # # GET /users/new.json
  # def new
  #   @user = User.new

  #   respond_to do |format|
  #     format.html # new.html.erb
  #     format.json { render json: @user }
  #   end
  # end

  # # GET /users/1/edit
  # def edit
  #   @user = User.find(params[:id])
  # end

  # # POST /users
  # # POST /users.json
  # def create
  #   @user = User.new(params[:user])

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render json: @user, status: :created, location: @user }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PUT /users/1
  # # PUT /users/1.json
  # def update
  #   @user = User.find(params[:id])

  #   respond_to do |format|
  #     if @user.update_attributes(params[:user])
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /users/1
  # # DELETE /users/1.json
  # def destroy
  #   @user = User.find(params[:id])
  #   @user.destroy

  #   respond_to do |format|
  #     format.html { redirect_to users_url }
  #     format.json { head :no_content }
  #   end
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account %><br />
    <%= f.text_field :account %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_sly.html.erb
<div class="wrap">
	<div class="scrollbar">
		<div class="handle">
			<div class="mousearea"></div>
		</div>
	</div>
	<div class="frame effects" id="effects">
		<ul class="clearfix">
			<% current_user.rooms.each do |room| %>
				<li>
					<%= link_to room.name, new_user_room_question_path(current_user, room) %>
			        <p>質問数:&nbsp;<%= room.questions.count %></p>
				</li>
			<% end %>
		</ul>
	</div>
	<div class="sly-controls center">
		<button class="btn prev"><i class="icon-chevron-left"></i></button>&nbsp;&nbsp;
		<button class="btn next"><i class="icon-chevron-right"></i></button>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="span3"></div><!--/span-->

<div class="span6"></div>

<div class="span3"></div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Account:</b>
  <%= @user.account %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>