config/routes.rb
Qoom::Application.routes.draw do

  devise_for :users

  match 'mail/new' => 'mail#create'

  resources :demands
  resources :users do
    resources :rooms do
      resources :questions do
        get "commentary", :on => :collection
      end
    end
  end

  authenticated :user do
    root :to => "top#index"
  end

  unauthenticated :user do
    root :to => "welcome#index"
  end

end

app/views/shared/_header_nav.html.erb
<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<div class="nav-collapse collapse">
  <ul class="nav pull-left">
    <% if user_signed_in? %>
      <li>
        <%= link_to user_rooms_path(current_user.id) do %>
          <i class="icon-edit"></i>ルームの編集
        <% end %>
      </li>
      <li><a href="#modal-logout" data-toggle="modal">Qoomへのご要望</a></li>
    <% end %>
  </ul>
  <ul class="nav pull-right">
    <% if user_signed_in? %>
      <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
    <% end %>
  </ul>
</div><!--/.nav-collapse -->

<div id="modal-logout" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="mdl_header_demand" aria-hidden="true">
  <div class="modal-header">
  	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="mdl_header_demand">Qoomへのご要望</h3>
  </div>
  <div class="modal-body">
  	<p id="demand_created_status"></p>
    <%= render partial: 'demands/form', :demand => @demand %>
  </div>
  <!--
  <div class="modal-footer">
  	<%#= link_to "ご要望一覧", demands_path, {:class => "btn primary"} %>
  </div>
  -->
</div>