config/routes.rb
Qoom::Application.routes.draw do

  devise_for :users

  match 'mail/new' => 'mail#create'

  resources :demands
  resources :users do
    resources :rooms do
      resources :questions do
        get "commentary", :on => :collection
      end
    end
  end

  authenticated :user do
    root :to => "top#index"
  end

  unauthenticated :user do
    root :to => "welcome#index"
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_one :users_rooms
  has_one :user, :through=>:users_rooms

  has_many :rooms_questions
  has_many :questions, :through=>:rooms_questions

  has_many :cooperations

  attr_accessible :name

  default_scope { order("created_at desc") }

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = current_user.rooms

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # # GET /rooms/1
  # # GET /rooms/1.json
  # def show
  #   @room = Room.find(params[:id])

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @room }
  #   end
  # end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    current_user.rooms.create(params[:room])

    respond_to do |format|
      @rooms = current_user.rooms
      format.html { redirect_to user_rooms_url current_user }
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    room = Room.find(params[:id])
    room.update_attributes(params[:room])

    respond_to do |format|
      @rooms = current_user.rooms
      format.html { redirect_to user_rooms_url current_user }
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to user_rooms_url current_user }
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for [current_user, @room], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                user_rooms_path(current_user), :class => 'btn' %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rooms/index.html.erb
<%- model_class = Room -%>
<div class="span4"></div>

<div class="span4">

  <div class="page-header">
    <h1>ルームの編集</h1>
  </div>
  <%= link_to '新規作成', new_user_room_path(current_user) %>
  <hr/>
  <table class="table table-striped">
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= link_to '編集', edit_user_room_path(current_user, room) %></td>
        <td><%= link_to '削除', user_room_path(current_user, room), method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
        <!--<td><%#= link_to "質問の実況を見る", commentary_user_room_questions_path( current_user.id, room.id ) %></td>-->
      </tr>
    <% end %>
  </table>

</div>

<div class="span4"></div>

app/views/rooms/new.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/rooms/show.html.erb
<%- model_class = Room -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @room.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              rooms_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_room_path(@room), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              room_path(@room),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>